//! Lucide icons (ISC licence, `assets/icons/LICENSE-lucide.txt`), embedded and tinted at run time.
//! One line per icon: add the SVG to `crates/ui-egui/assets/icons/` and a line here. A few
//! icons Lucide has no match for are MarkupCraft's own, in `assets/icons-own/`.

pub static ICONS: &[(&str, &[u8])] = &[
    ("pencil-ruler", include_bytes!("../assets/icons/pencil-ruler.svg")),
    ("flag", include_bytes!("../assets/icons/flag.svg")),
    ("keyboard", include_bytes!("../assets/icons/keyboard.svg")),
    ("arrow-down", include_bytes!("../assets/icons/arrow-down.svg")),
    ("arrow-up", include_bytes!("../assets/icons/arrow-up.svg")),
    ("download", include_bytes!("../assets/icons/download.svg")),
    ("upload", include_bytes!("../assets/icons/upload.svg")),
    ("spell-check", include_bytes!("../assets/icons/spell-check.svg")),
    ("frame", include_bytes!("../assets/icons/frame.svg")),
    (
        "circle-dot-dashed",
        include_bytes!("../assets/icons/circle-dot-dashed.svg"),
    ),
    ("triangle-right", include_bytes!("../assets/icons/triangle-right.svg")),
    ("box", include_bytes!("../assets/icons/box.svg")),
    ("radius", include_bytes!("../assets/icons/radius.svg")),
    ("diameter", include_bytes!("../assets/icons/diameter.svg")),
    ("save-all", include_bytes!("../assets/icons/save-all.svg")),
    ("paintbrush", include_bytes!("../assets/icons/paintbrush.svg")),
    ("copy-plus", include_bytes!("../assets/icons/copy-plus.svg")),
    ("flip-vertical-2", include_bytes!("../assets/icons/flip-vertical-2.svg")),
    (
        "flip-horizontal-2",
        include_bytes!("../assets/icons/flip-horizontal-2.svg"),
    ),
    (
        "align-end-horizontal",
        include_bytes!("../assets/icons/align-end-horizontal.svg"),
    ),
    (
        "align-center-horizontal",
        include_bytes!("../assets/icons/align-center-horizontal.svg"),
    ),
    (
        "align-start-horizontal",
        include_bytes!("../assets/icons/align-start-horizontal.svg"),
    ),
    (
        "align-end-vertical",
        include_bytes!("../assets/icons/align-end-vertical.svg"),
    ),
    (
        "align-center-vertical",
        include_bytes!("../assets/icons/align-center-vertical.svg"),
    ),
    (
        "align-start-vertical",
        include_bytes!("../assets/icons/align-start-vertical.svg"),
    ),
    ("align-center", include_bytes!("../assets/icons/align-center.svg")),
    ("align-left", include_bytes!("../assets/icons/align-left.svg")),
    ("align-justify", include_bytes!("../assets/icons/align-justify.svg")),
    ("align-right", include_bytes!("../assets/icons/align-right.svg")),
    (
        "arrow-left-right",
        include_bytes!("../assets/icons/arrow-left-right.svg"),
    ),
    ("arrow-up-right", include_bytes!("../assets/icons/arrow-up-right.svg")),
    ("bold", include_bytes!("../assets/icons/bold.svg")),
    ("bookmark", include_bytes!("../assets/icons/bookmark.svg")),
    ("camera", include_bytes!("../assets/icons/camera.svg")),
    ("check", include_bytes!("../assets/icons/check.svg")),
    ("chevron-down", include_bytes!("../assets/icons/chevron-down.svg")),
    ("chevron-left", include_bytes!("../assets/icons/chevron-left.svg")),
    ("chevron-right", include_bytes!("../assets/icons/chevron-right.svg")),
    ("chevrons-left", include_bytes!("../assets/icons/chevrons-left.svg")),
    ("chevrons-right", include_bytes!("../assets/icons/chevrons-right.svg")),
    ("circle", include_bytes!("../assets/icons/circle.svg")),
    ("circle-dashed", include_bytes!("../assets/icons/circle-dashed.svg")),
    ("circle-help", include_bytes!("../assets/icons/circle-help.svg")),
    ("clipboard-paste", include_bytes!("../assets/icons/clipboard-paste.svg")),
    ("clock", include_bytes!("../assets/icons/clock.svg")),
    ("cloud", include_bytes!("../assets/icons/cloud.svg")),
    ("columns-3", include_bytes!("../assets/icons/columns-3.svg")),
    ("compass", include_bytes!("../assets/icons/compass.svg")),
    ("copy", include_bytes!("../assets/icons/copy.svg")),
    (
        "ellipsis-vertical",
        include_bytes!("../assets/icons/ellipsis-vertical.svg"),
    ),
    ("eraser", include_bytes!("../assets/icons/eraser.svg")),
    ("eye", include_bytes!("../assets/icons/eye.svg")),
    ("eye-off", include_bytes!("../assets/icons/eye-off.svg")),
    ("file-down", include_bytes!("../assets/icons/file-down.svg")),
    ("file-minus", include_bytes!("../assets/icons/file-minus.svg")),
    ("file-output", include_bytes!("../assets/icons/file-output.svg")),
    ("file-plus", include_bytes!("../assets/icons/file-plus.svg")),
    (
        "file-spreadsheet",
        include_bytes!("../assets/icons/file-spreadsheet.svg"),
    ),
    ("file-text", include_bytes!("../assets/icons/file-text.svg")),
    ("file-x", include_bytes!("../assets/icons/file-x.svg")),
    ("files", include_bytes!("../assets/icons/files.svg")),
    ("filter", include_bytes!("../assets/icons/filter.svg")),
    ("folder-open", include_bytes!("../assets/icons/folder-open.svg")),
    ("grid-3x3", include_bytes!("../assets/icons/grid-3x3.svg")),
    ("hand", include_bytes!("../assets/icons/hand.svg")),
    ("hash", include_bytes!("../assets/icons/hash.svg")),
    ("highlighter", include_bytes!("../assets/icons/highlighter.svg")),
    ("info", include_bytes!("../assets/icons/info.svg")),
    ("italic", include_bytes!("../assets/icons/italic.svg")),
    ("layers", include_bytes!("../assets/icons/layers.svg")),
    ("layout-grid", include_bytes!("../assets/icons/layout-grid.svg")),
    ("list", include_bytes!("../assets/icons/list.svg")),
    ("list-checks", include_bytes!("../assets/icons/list-checks.svg")),
    ("lock", include_bytes!("../assets/icons/lock.svg")),
    ("lock-open", include_bytes!("../assets/icons/lock-open.svg")),
    ("maximize", include_bytes!("../assets/icons/maximize.svg")),
    ("message-square", include_bytes!("../assets/icons/message-square.svg")),
    (
        "message-square-plus",
        include_bytes!("../assets/icons/message-square-plus.svg"),
    ),
    (
        "message-square-quote",
        include_bytes!("../assets/icons/message-square-quote.svg"),
    ),
    ("minus", include_bytes!("../assets/icons/minus.svg")),
    ("mouse-pointer-2", include_bytes!("../assets/icons/mouse-pointer-2.svg")),
    ("move", include_bytes!("../assets/icons/move.svg")),
    ("move-right", include_bytes!("../assets/icons/move-right.svg")),
    ("panel-left", include_bytes!("../assets/icons/panel-left.svg")),
    ("panel-right", include_bytes!("../assets/icons/panel-right.svg")),
    ("pen-line", include_bytes!("../assets/icons/pen-line.svg")),
    ("pen-tool", include_bytes!("../assets/icons/pen-tool.svg")),
    ("pentagon", include_bytes!("../assets/icons/pentagon.svg")),
    ("pin", include_bytes!("../assets/icons/pin.svg")),
    ("plus", include_bytes!("../assets/icons/plus.svg")),
    ("printer", include_bytes!("../assets/icons/printer.svg")),
    (
        "rectangle-horizontal",
        include_bytes!("../assets/icons/rectangle-horizontal.svg"),
    ),
    ("redo-2", include_bytes!("../assets/icons/redo-2.svg")),
    ("rotate-ccw", include_bytes!("../assets/icons/rotate-ccw.svg")),
    ("rotate-cw", include_bytes!("../assets/icons/rotate-cw.svg")),
    ("rows-3", include_bytes!("../assets/icons/rows-3.svg")),
    ("ruler", include_bytes!("../assets/icons/ruler.svg")),
    ("save", include_bytes!("../assets/icons/save.svg")),
    ("scan", include_bytes!("../assets/icons/scan.svg")),
    ("scissors", include_bytes!("../assets/icons/scissors.svg")),
    ("search", include_bytes!("../assets/icons/search.svg")),
    ("settings", include_bytes!("../assets/icons/settings.svg")),
    (
        "sliders-horizontal",
        include_bytes!("../assets/icons/sliders-horizontal.svg"),
    ),
    ("spline", include_bytes!("../assets/icons/spline.svg")),
    ("square", include_bytes!("../assets/icons/square.svg")),
    ("square-dashed", include_bytes!("../assets/icons/square-dashed.svg")),
    (
        "square-dashed-mouse-pointer",
        include_bytes!("../assets/icons/square-dashed-mouse-pointer.svg"),
    ),
    (
        "squares-subtract",
        include_bytes!("../assets/icons/squares-subtract.svg"),
    ),
    ("stamp", include_bytes!("../assets/icons/stamp.svg")),
    ("star", include_bytes!("../assets/icons/star.svg")),
    ("sticky-note", include_bytes!("../assets/icons/sticky-note.svg")),
    ("strikethrough", include_bytes!("../assets/icons/strikethrough.svg")),
    ("tag", include_bytes!("../assets/icons/tag.svg")),
    (
        "text-cursor-input",
        include_bytes!("../assets/icons/text-cursor-input.svg"),
    ),
    ("text-select", include_bytes!("../assets/icons/text-select.svg")),
    ("trash", include_bytes!("../assets/icons/trash.svg")),
    ("trash-2", include_bytes!("../assets/icons/trash-2.svg")),
    ("type", include_bytes!("../assets/icons/type.svg")),
    ("underline", include_bytes!("../assets/icons/underline.svg")),
    ("undo-2", include_bytes!("../assets/icons/undo-2.svg")),
    ("wrench", include_bytes!("../assets/icons/wrench.svg")),
    ("x", include_bytes!("../assets/icons/x.svg")),
    ("zoom-in", include_bytes!("../assets/icons/zoom-in.svg")),
    ("zoom-out", include_bytes!("../assets/icons/zoom-out.svg")),
    // MarkupCraft's own icons (contributor-original, `assets/icons-own/`).
    ("contrast", include_bytes!("../assets/icons-own/contrast.svg")),
    ("picture", include_bytes!("../assets/icons-own/picture.svg")),
];
