//! Lucide icons (ISC licence, `assets/icons/LICENSE-lucide.txt`), embedded and tinted at run time.
//! One line per icon: add the SVG to `crates/ui-egui/assets/icons/` and a line here.

pub static ICONS: &[(&str, &[u8])] = &[
    (
        "arrow-left-right",
        include_bytes!("../assets/icons/arrow-left-right.svg"),
    ),
    ("bookmark", include_bytes!("../assets/icons/bookmark.svg")),
    ("chevron-down", include_bytes!("../assets/icons/chevron-down.svg")),
    ("chevron-left", include_bytes!("../assets/icons/chevron-left.svg")),
    ("chevron-right", include_bytes!("../assets/icons/chevron-right.svg")),
    ("chevrons-left", include_bytes!("../assets/icons/chevrons-left.svg")),
    ("chevrons-right", include_bytes!("../assets/icons/chevrons-right.svg")),
    ("circle-help", include_bytes!("../assets/icons/circle-help.svg")),
    ("circle", include_bytes!("../assets/icons/circle.svg")),
    ("clipboard-paste", include_bytes!("../assets/icons/clipboard-paste.svg")),
    ("cloud", include_bytes!("../assets/icons/cloud.svg")),
    ("copy", include_bytes!("../assets/icons/copy.svg")),
    ("eye-off", include_bytes!("../assets/icons/eye-off.svg")),
    ("eye", include_bytes!("../assets/icons/eye.svg")),
    ("file-down", include_bytes!("../assets/icons/file-down.svg")),
    ("file-text", include_bytes!("../assets/icons/file-text.svg")),
    ("file-x", include_bytes!("../assets/icons/file-x.svg")),
    ("files", include_bytes!("../assets/icons/files.svg")),
    ("folder-open", include_bytes!("../assets/icons/folder-open.svg")),
    ("grid-3x3", include_bytes!("../assets/icons/grid-3x3.svg")),
    ("hand", include_bytes!("../assets/icons/hand.svg")),
    ("hash", include_bytes!("../assets/icons/hash.svg")),
    ("highlighter", include_bytes!("../assets/icons/highlighter.svg")),
    ("info", include_bytes!("../assets/icons/info.svg")),
    ("layers", include_bytes!("../assets/icons/layers.svg")),
    ("layout-grid", include_bytes!("../assets/icons/layout-grid.svg")),
    ("list-checks", include_bytes!("../assets/icons/list-checks.svg")),
    ("list", include_bytes!("../assets/icons/list.svg")),
    ("lock", include_bytes!("../assets/icons/lock.svg")),
    ("maximize", include_bytes!("../assets/icons/maximize.svg")),
    ("message-square", include_bytes!("../assets/icons/message-square.svg")),
    ("mouse-pointer-2", include_bytes!("../assets/icons/mouse-pointer-2.svg")),
    ("move-right", include_bytes!("../assets/icons/move-right.svg")),
    ("panel-left", include_bytes!("../assets/icons/panel-left.svg")),
    ("panel-right", include_bytes!("../assets/icons/panel-right.svg")),
    ("pen-line", include_bytes!("../assets/icons/pen-line.svg")),
    ("pentagon", include_bytes!("../assets/icons/pentagon.svg")),
    ("printer", include_bytes!("../assets/icons/printer.svg")),
    (
        "rectangle-horizontal",
        include_bytes!("../assets/icons/rectangle-horizontal.svg"),
    ),
    ("redo-2", include_bytes!("../assets/icons/redo-2.svg")),
    ("rows-3", include_bytes!("../assets/icons/rows-3.svg")),
    ("ruler", include_bytes!("../assets/icons/ruler.svg")),
    ("save", include_bytes!("../assets/icons/save.svg")),
    ("scan", include_bytes!("../assets/icons/scan.svg")),
    ("scissors", include_bytes!("../assets/icons/scissors.svg")),
    ("search", include_bytes!("../assets/icons/search.svg")),
    ("settings", include_bytes!("../assets/icons/settings.svg")),
    (
        "sliders-horizontal",
        include_bytes!("../assets/icons/sliders-horizontal.svg"),
    ),
    ("spline", include_bytes!("../assets/icons/spline.svg")),
    (
        "square-dashed-mouse-pointer",
        include_bytes!("../assets/icons/square-dashed-mouse-pointer.svg"),
    ),
    ("square", include_bytes!("../assets/icons/square.svg")),
    ("stamp", include_bytes!("../assets/icons/stamp.svg")),
    ("sticky-note", include_bytes!("../assets/icons/sticky-note.svg")),
    ("trash-2", include_bytes!("../assets/icons/trash-2.svg")),
    ("type", include_bytes!("../assets/icons/type.svg")),
    ("undo-2", include_bytes!("../assets/icons/undo-2.svg")),
    ("wrench", include_bytes!("../assets/icons/wrench.svg")),
    ("x", include_bytes!("../assets/icons/x.svg")),
    ("zoom-in", include_bytes!("../assets/icons/zoom-in.svg")),
    ("zoom-out", include_bytes!("../assets/icons/zoom-out.svg")),
];
